import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillTwitterCircle, AiFillLinkedin } from 'react-icons/ai'
import Image from "next/image"
import deved from "../public/dev-ed-wave.png";
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import { useState } from "react";
// import { motionTwo } from "framer-motion-3d"
import { motion } from 'framer-motion';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen '>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-lg font-medium font-burtons dark:text-white'>Ryan Dutton Portfolio</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl' />
              </li>
              <li className='px-5 py-2 ml-8 bg-gradient-to-r from-cyan-500 to-teal-500 text-white rounded-md'>
                <a href='./page2.js'>CV</a>
              </li>
            </ul>

          </nav>
          <div className='text-center p-10'>
            <motion.div initial='hidden' animate='visible' variants={{
              hidden: {

                y: -100,
                opacity: 0
              },
              visible: {
                y: 0,
                opacity: 1,
                transition: {
                  delay: .4
                }
              },
            }}>
              <h2 className='text-5xl py-2 text-gray-900 font-semibold md:text-6xl dark:text-white'>Ryan Dutton</h2>
            </motion.div>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-gray-400'>Developer and Designer</h3>
            <p className='text-md py-5 text-gray-700 leading-8 md:text-xl max-w-lg mx-auto dark:text-gray-300'>
              Crafting digital solutions with creativity and code
              Crafting digital solutions with creativity and code
              Crafting digital solutions with creativity and code
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-10'>
            <AiFillLinkedin />
            <AiFillTwitterCircle />
          </div>
          <motion.div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96' whileHover={{
            position: 'relative',
            zIndex: 1,
            scale: 1.2,
            transition: {
              duration: .2,
            }
          }}>
            <Image src={deved} layout='fill' objectFit='cover' />
          </motion.div>
        </section>

        <section>

          <div>

            <h3 className='text-3xl py-1 font-semibold dark:text-white'>Design Process</h3>
            <p className='text-md py-5 text-gray-700 leading-8'>
              An example of design process around 5 different steps
            </p>

          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center mx-auto justify-center shadow-lg p-10 rounded-xl my-10'>
              <Image className='inline' src={code} width={100} height={100} />
              <h4 className='text-teal-500'>Research</h4>
              <p className='text-md py-2 text-gray-700'>A short description of design and development research methods</p>



            </div>
            <div className='text-center mx-auto justify-center shadow-lg p-10 rounded-xl my-10'>
              <Image className='inline' src={design} width={100} height={100} />
              <h4 className='text-teal-500'>Experimentation</h4>
              <p className='text-md py-2 text-gray-700'>A short description of design and development research methods</p>


            </div>
            <div className='text-center mx-auto justify-center shadow-lg p-10 rounded-xl my-10'>
              <Image className='inline' src={consulting} width={100} height={100} />
              <h4 className='text-teal-500'>Development</h4>
              <p className='text-md py-2 text-gray-700'>A short description of design and development research methods</p>


            </div>
          </div>
          <div>

            <h4 className='text-2xl text-center'>Design Skills</h4>
            <div className='flex justify-center py-2'>
              <p className='text-gray-700 px-4'>Figma</p>
              <p className='text-gray-700 px-4'>Photoshop</p>
              <p className='text-gray-700 px-4'>Illustrator</p>
              <p className='text-gray-700 px-4'>After Effects</p>
            </div>

            <div>
              <h4 className='text-2xl text-center'>Developer Skills</h4>
              <div className='flex justify-center py-2'>
                <p className='text-gray-700 px-4'>React</p>
                <p className='text-gray-700 px-4'>Three.js</p>
                <p className='text-gray-700 px-4'>webgl</p>
                <p className='text-gray-700 px-4'>MongoDB</p>
              </div>
            </div>
          </div>

        </section>

        <section>
          <h3 className='text-3xl py-1'>Portfolio</h3>
          <p className='text-md py-2 text-gray-700'>A short description of design and development research methods</p>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout="responsive" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout="responsive" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout="responsive" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout="responsive" />
            </div>
          </div>
        </section>

        <section>

        </section>

      </main>
    </div>
  )
}
